### ISSUE TITLE
Seems like a good idea to open a "Discussions" tab, as that can encourage community talks to solve any issues. 

### ISSUE THREAD

**Issue by 01GOD** [lsdlsd88/JC4827W543#1]
Hi, 

Thanks for posting those. I tried for hours to get any of the demos to compile by doing the steps in the included PDF, but sadly all of them had compile errors thus far. 

 Seems like a good idea to open a "Discussions" tab, as that can encourage community talks to solve any issues. 

By the way, found a way to make any of those compile on a JC4827W543 yet? If did, explaining how would be appreciated! (and would be good to have stored here on the repo anyway)

Thanks in advance!

**Comment by lsdlsd88** [comment]
done
