### ISSUE TITLE
Found a way to get any of those to compile? (Posting this as a new thread so it is easy to find)

### ISSUE THREAD

**Issue by 01GOD** [lsdlsd88/JC4827W543#2]
Hi, 

Found a way to make any of those demos compile on a JC4827W543 yet? If did, explaining how would be appreciated! (and would be good to have stored here on the repo anyway)

Thanks in advance!

**Comment by lsdlsd88** [comment]
please open as discussion

**Comment by 01GOD** [comment]
Honestly solving a compilation issue seems better to keep in the "Issues" section. It's not a personal project, so don't be worried about it being listed as an "Issue". I can open a discussion also though.
